# permissions for end users to view airflowclusters.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: airflow-operator
    app.kubernetes.io/managed-by: kustomize
  name: airflowclusters-viewer-role
rules:
- apiGroups:
  - airflow.kubedoop.dev
  resources:
  - airflowclusters
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - airflow.kubedoop.dev
  resources:
  - airflowclusters/status
  verbs:
  - get
