# permissions for end users to edit airflowclusters.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: airflow-operator
    app.kubernetes.io/managed-by: kustomize
  name: airflowclusters-editor-role
rules:
- apiGroups:
  - airflow.kubedoop.dev
  resources:
  - airflowclusters
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - airflow.kubedoop.dev
  resources:
  - airflowclusters/status
  verbs:
  - get
