# This rule is not used by the project airflow-operator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants read-only access to airflow.kubedoop.dev.
# This role is intended for users who need visibility into these resources
# without permissions to modify them. It is ideal for monitoring purposes and limited-access viewing.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: airflow-operator
    app.kubernetes.io/managed-by: kustomize
  name: airflowcluster-viewer-role
rules:
- apiGroups:
  - airflow.kubedoop.dev
  resources:
  - airflowclusters
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - airflow.kubedoop.dev
  resources:
  - airflowclusters/status
  verbs:
  - get
